### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IIIef** [JoinedSenses/TF2-Sentry-QuickBuild#1]
Good afternoon, an error appears periodically, you can fix it.

L 06/03/2020 - 19:43:29: Info (map "xxx") (file "D:\TF2\xxx\tf\addons\sourcemod\logs\errors_20200603.log")
L 06/03/2020 - 19:43:29: [SM] Exception reported: Entity 1049 is not valid
L 06/03/2020 - 19:43:29: [SM] Blaming: sentrybuild.smx
L 06/03/2020 - 19:43:29: [SM] Call stack trace:
L 06/03/2020 - 19:43:29: [SM]   [0] SDKCall
L 06/03/2020 - 19:43:29: [SM]   [1] Line 270, G:\Documents\TF2\SourceMod 1.9.0-6245\addons\sourcemod\scripting\sentrybuild.sp::FrameCallback_StartBuilding
L 06/03/2020 - 19:43:29: [SM] Exception reported: Entity 1049 is not valid
L 06/03/2020 - 19:43:29: [SM] Blaming: sentrybuild.smx
L 06/03/2020 - 19:43:29: [SM] Call stack trace:
L 06/03/2020 - 19:43:29: [SM]   [0] SDKCall
L 06/03/2020 - 19:43:29: [SM]   [1] Line 274, G:\Documents\TF2\SourceMod 1.9.0-6245\addons\sourcemod\scripting\sentrybuild.sp::FrameCallback_FinishBuilding

**Comment by JoinedSenses** [comment]
Can you provide more information about when this happens?

**Comment by IIIef** [comment]
This happens very rarely on different servers.

**Comment by JoinedSenses** [comment]
I mean the circumstances. Do you have any information on what causes this to happen? I've never seen these errors. The only thing I can think of is somehow within a single game frame someone has built an object and destroyed it immediately - which would have to be extremely fast.

**Comment by JoinedSenses** [comment]
Addressed in https://github.com/JoinedSenses/TF2-Sentry-QuickBuild/commit/92db07ec29409a4dae6fb0dbd648a3f8206e7cc1
